<div id="blog-part" class="px-5 wrapper-body-padding">
    <section id="blog-item-head" class="blog-item">
        <div class="container">
            <div class="row">
            	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">	
                    <div class="item-head-content">
                    	<h1>3D printing a drone and drone parts</h1>
                    </div>    
            	</div>
            </div>
        </div>
    </section>
    <section id="blog-item-block">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12"> 
                    <div class="item-block-content">
                        <p>Ever since their earliest days, humans have always been fascinated with what lies in the infiniteness of the sky. This same fascination inspired generations of visionaries from the Wright Brothers to Elon Musk to push humanity beyond their limits of “reality”.</p>
                        <p>The latest trend satisfying our urge to go sky high is the all-powerful drones or UAV’s, and they’re as revolutionary as fun. First introduced (commercially) back in 2013 by multi-billionaire and CEO Jeff Bezos and a means to execute deliveries (called the Prime Air Drone Project), they have expanded to fields ranging from Disaster Management, City Planning, protecting endangered species, defense, and even telecom, the drones were all set to rule the skies of the future and make life ever so comfortable, the only limitation, however, was the exorbitant cost to make a drone. It was only a dream for designers to easily tweak, modify and build them.</p>
                        <p>That’s when 3D printing came to the rescue! “Imagine being able to customize and build drones just on a whim,” it said. In simpler words with its nature of additive manufacturing and its ever-growing versatility in materials, 3D printing has democratized building drones. We can already print major components like frames, camera mounts, and protective gear. </p>
                        <p>A wide choice of materials allows designers to make much lighter and stronger designs while also giving them geometric freedom in drone and aircraft designs. This allows drones to fly faster and for longer durations as a result of which the DRL RacerX recently set a world record at a speed of 263.1 kmph (179.6 mph).</p>
                        <p>Other companies are also pouncing on the opportunity; Blue Robotics are already using 3D printing. Blue Robotics is working on preparing their own submarine drones to explore the dark secrets of seven seas which are beyond the reach of men.</p>
                        <p>Yuki Ogasarawa along with Ryo Kumeda printed their drone designed to be handy in the earthquake-prone areas on Japan in case of disaster. It allows emergency services to see and observe real-time images to find survivors quickly and efficiently.</p>
                        <p>Thanks to 3D printing, UAVs as a whole have progressed beyond their years. Air shows have become vastly popular as people come together on airstrips to show off their drone skills and aircraft models.</p>
                        <p>But 3D printing doesn’t plan to stop anywhere near just models. Its hit the aerospace industry and it has hit it big. The aerospace industry has welcomed 3D printing since its nascent days, dating as back as 1989, and it has only increased, to the point where in 2015 16% of the $4.9 bil revenue of 3D Printing industry was generated by the aerospace industry. Techniques like SLA and material jetting to produce highly detailed aircraft models and components while maintaining weight and stability. It further allows tailoring parts to a specific aircraft thus maximizing fuel efficiency.</p>
                        <p>As 3D printing continues to grow in application to different industries, it is no surprise 3D printed drones are coming to stay and will turn things for the better. It’ll continue to revolutionize aircraft designs and UAV’s will allow humans to reach way beyond their territories leading better and safer lives.</p>
                    </div>    
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="project-intro-content">
                        <h4 class="text-center">Tell Us What You're Making</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-4 offset-xl-1 col-lg-4 offset-lg-1 col-md-4 offset-md-1 col-sm-12 offset-sm-0 col-12 offset-0">
                    <div class="project-intro-content">
                        <p class="text-center">Have a design or project in mind? <br>Design with 3D Usher</p>
                        <div class="row"> 
                            <div class="col-xl-6 offset-xl-3 col-lg-6 offset-lg-3 col-md-6 offset-md-3">
                                <a href="<?= base_url('describe-project'); ?>" class="btn btn-primary Pbtn">DESCRIBE PROJECT</a>
                            </div>   
                        </div>      
                    </div>
                </div>
                <div class="col-xl-1 col-lg-1 col-md-1 col-sm-12 col-12">    
                    <span class="d-md-block vr-divider"></span>
                </div>    
                <div class="col-xl-4 offset-xl-1 col-lg-4 offset-lg-1 col-md-4 offset-md-1 col-sm-12 offset-sm-0 col-12 offset-0">
                    <div class="project-intro-content">
                        <p class="text-center">Looking for manufacturing solutions?<br> Upload your 3D Design and get instant quote</p>
                        <div class="row"> 
                            <div class="col-xl-6 offset-xl-3 col-lg-6 offset-lg-3 col-md-6 offset-md-3">    
                                <a href="<?= base_url('manufacture'); ?>" class="btn btn-primary Pbtn">UPLOAD FILES</a>
                            </div>
                        </div>               
                    </div>
                </div>
            </div>
            <div class="row">    
                <div class="col-xl-10 offset-xl-1 col-lg-10 offset-lg-1 col-md-10 offset-md-1 col-sm-12 offset-sm-0 col-12 offset-0">
                    <div class="row my-3">
                        <div class="col">
                            <hr class="hr-divider">
                        </div>
                        <div class="col-auto m-auto">
                            OR
                        </div>
                        <div class="col">
                            <hr class="hr-divider">
                        </div>
                    </div>
                </div>    
            </div>         
            <div class="row">
                <div class="col-xl-4 offset-xl-4 col-lg-4 offset-lg-4 col-md-4 offset-md-4 col-sm-12 offset-sm-0 col-12 offset-0">
                    <div class="project-intro-content">
                        <a href="<?= base_url('contact-us'); ?>" class="btn btn-primary Abtn">CONTACT SALES</a>
                    </div>
                </div>
            </div>
            <?php
                if (empty($usher_id)) {
            ?>
            <hr>
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-6 col-xs-12">
                    <div class="item-block-content">
                        <h4 class="center-align">Register Now</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 offset-xl-2 col-lg-8 offset-lg-2 col-md-8 offset-md-2 col-sm-12 col-xs-12">    
                    <div class="item-block-content">
                        <p>Design, Manufacture and track you order in single place. Register with 3D Usher to explore more.</p>
                        <div class="col-xl-4 offset-xl-4 col-lg-4 offset-lg-4 col-md-4 offset-md-4 col-sm-12 col-xs-12">
                            <a class="btn btn-primary Pbtn" href="<?= base_url('register'); ?>">REGISTER</a>
                        </div>
                    </div>
                </div>
            </div>
            <?php
                }
            ?>    
        </div>
    </section>
</div>